cours_python/django-web-app/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/change', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete', views.band_delete, name='band-delete'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/change', views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete', views.listing_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact-us'),
    path('email-sent/', views.email_sent, name='email-sent'),
    path('about-us/', views.about, name='about'),
]

cours_python/django-web-app/merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=50)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Listing(models.Model):
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.title}"

cours_python/django-web-app/merchex/listings/forms.py
from django import forms
from .models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

cours_python/django-web-app/merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .models import Band
from .models import Listing
from .forms import ContactUsForm, BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)

        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def band_update(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)

        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {'form': form})


def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def listing_list(request):
    all_listings = Listing.objects.all()
    return render(request,
                  'listings/listing_list.html',
                  {'all_listings': all_listings})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)

        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request,
                  'listings/listing_create.html',
                  {'form': form})


def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)

        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                  'listings/listing_update.html',
                  {'form': form})


def listing_delete(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')
    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f"Message from {form.cleaned_data['name'] or 'anonyme'} via MerchEx Contact Us form",
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )

            return redirect('email-sent')
    else:
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  {'form': form})


def email_sent(request):
    return render(request,
                  'listings/email-sent.html')


def about(request):
    return render(request,
                  'listings/about-us.html')

cours_python/django-web-app/merchex/listings/templates/listings/about-us.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>À propos</h1>
<p>Nous adorons merch !</p>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}


{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active | yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<h3>Annonces :</h3>
<u>
    {% for listing in band.listing_set.all %}
    <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
</u>

</br>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

</br>
</br>

<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

</br>
</br>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[modifier]</a>
        - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/base.html
{% load static %}


<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>

    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Listings</a>
            <a href="{% url 'contact-us' %}">Contact</a>
            <a href="{% url 'about' %}">About</a>
        </nav>

        {% block content %}{% endblock %}
    </body>
</html>

cours_python/django-web-app/merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Nous contacter</h1>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/email-sent.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Email envoyé</h1>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Créer une nouvelle annonce</h1>

<form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce' : {{ listing.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}


{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
    <li>Groupe : {{ listing.band }}</li>
    <li>Année : {{ listing.year }}</li>
    <li>Vendu : {{ listing.sold | yesno }}</li>
</ul>

<p>{{ listing.description }}</p>

</br>

<a href="{% url 'listing-update' listing.id %}">Modifier cette annonce</a>

</br>
</br>

<a href="{% url 'listing-delete' listing.id %}">Supprimer cette annonce</a>

</br>
</br>

<a href="{% url 'listing-list' %}">Retour à tous les listings</a>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Listing</h1>

<a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>

<ul>
    {% for listing in all_listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[modifier]</a>
        - <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

cours_python/django-web-app/merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}


{% block content %}

<h1>Mise à jour de l'annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}